### ISSUE TITLE
请问有没有指定nodejs版本的？

### ISSUE THREAD

**Issue by petcat** [ebb-io/ebbx#4]
测试了两个版本都报错，10正式版和最高11都是

先是报的漏洞风险
added 1428 packages from 787 contributors and audited 12404 packages in 29.191s
found 2 vulnerabilities (1 low, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details

用 npm audit fix 修复以后，npm run build 时继续报错
```
ERROR in ./src/main.js
Module build failed: Error: No ESLint configuration found.
```

**Comment by ebb-anime** [comment]
這些報錯只是NPM的安全性警告
運行`npm run build`即可編譯為生產環境版本

注意必須於根目錄下建立`static`文件夾
否則`npm run build`會出現錯誤
編譯完後的檔案會出現於`dist`文件夾內

<img width="540" src="https://user-images.githubusercontent.com/46046357/53002411-9a820980-3467-11e9-90d7-bb93bd20738f.png">

**Comment by petcat** [comment]
感谢回复! 之前是没有建立 static 文件夾，但我又测试一下，还是报错。
我是在服务器上直接构建，nodejs  版本为v10.15.1 ,  npm 版本为 v6.4.1

报错信息如下：
![](https://i.loli.net/2019/02/20/5c6c62cd966fe.png)

**Comment by ebb-anime** [comment]
可能是因為你曾運行`npm audit fix`導致代碼被修改
請嘗試重新git clone一次
